---
- name: mac-dev-bootstrap
  hosts: all
  roles:
#    - homebrew
#    - ohmyzsh
#    - sdkman
    - iterm2

#  tasks:
#    - name: "Ansible | List all known variables and facts"
#      debug:
#        var: hostvars[inventory_hostname]
#
#    - name: asd
#      debug:
#        msg: '{{ ansible_user_dir }}'
#
#    - name: playbook_dir
#      debug:
#        msg: '{{ playbook_dir }}'
