---
- name: Mac Dev Bootstrap
  hosts: all
  vars:
    playbook_retries: 10
    playbook_delay: 3
  roles:
    # --------------------------------------------------------------------------
    # Tools to install/configure
    # --------------------------------------------------------------------------
    - {role: mac, tags: [mac, personal, work]}
    - {role: xcode, tags: [xcode, personal, work]}
    - {role: homebrew_common, tags: [homebrew, personal, work]}
    - {role: homebrew_personal, tags: [personal]}
    - {role: homebrew_work, tags: [work]}
    - {role: python, tags: [python, personal, work]}
    - {role: quicklook, tags: [quicklook, personal, work]}
    - {role: ohmyzsh, tags: [ohmyzsh, sdkman, nvm, gcloud, personal, work]}
    - {role: sdkman, tags: [sdkman, personal, work]}
    - {role: iterm2, tags: [iterm2, personal, work]}
    - {role: nvm, tags: [nvm, personal, work]}
    - {role: vimrc, tags: [vimrc, personal, work]}
    - {role: gcloud, tags: [gcloud, personal, work]}
    - {role: ai_instructions, tags: [ai_instructions, personal, work]}
    # --------------------------------------------------------------------------
    # Post installation
    # --------------------------------------------------------------------------
    - {role: cleanup, tags: [cleanup, personal, work]}
    # --------------------------------------------------------------------------
    # For debugging purpose
    # --------------------------------------------------------------------------
    - {role: debug, tags: [never, debug]}
