---
- name: mac-dev-bootstrap
  hosts: all
  roles:
    - homebrew
    - ohmyzsh   # Expose `ohmyzsh_conf_dir` var for other roles below to use
    - sdkman
    - iterm2
    - nvm

#  tasks:
#    - name: "Ansible | List all known variables and facts"
#      debug:
#        var: hostvars[inventory_hostname]
#
#    - name: asd
#      debug:
#        msg: '{{ ansible_user_dir }}'
#
#    - name: playbook_dir
#      debug:
#        msg: '{{ playbook_dir }}'
