---
- name: mac-dev-bootstrap
  hosts: all
  roles:
    #--------------------------------------------------------------------------
    # Other roles may depend on these roles
    #--------------------------------------------------------------------------
    #    - homebrew
    #    - python
    - ohmyzsh
    #    #--------------------------------------------------------------------------
    #    # Standalone tools
    #    #--------------------------------------------------------------------------
    #    - sdkman
    #    - iterm2
    #    - nvm
    #    - vimrc
    - gcloud
    #--------------------------------------------------------------------------
    # Post installation
    #--------------------------------------------------------------------------
#    - cleanup
#    - debug
