---
- name: mac-dev-bootstrap
  hosts: all
  roles:
    #--------------------------------------------------------------------------
    # Other roles may depend on these roles
    #--------------------------------------------------------------------------
    - homebrew
    - python
    - ohmyzsh
    #--------------------------------------------------------------------------
    # Standalone tools
    #--------------------------------------------------------------------------
    - sdkman
    - iterm2
    - nvm
    - vimrc
    #--------------------------------------------------------------------------
    # Post installation
    #--------------------------------------------------------------------------
    - cleanup
#  tasks:
#    - name: "Ansible | List all known variables and facts"
#      debug:
#        var: hostvars[inventory_hostname]
