---
- name: mac-dev-bootstrap
  hosts: all
  roles:
    - ohmyzsh
    - sdkman

#  tasks:
#    - name: "Ansible | List all known variables and facts"
#      debug:
#        var: hostvars[inventory_hostname]
#
#    - name: asd
#      debug:
#        msg: '{{ ansible_user_dir }}'
#
#    - name: playbook_dir
#      debug:
#        msg: '{{ playbook_dir }}'


#      user_home: "{{ user_home }}"
#      sdkman_flush_caches_before:
#        - temp
#      sdkman_flush_caches_after:
#        - archives
#        - broadcast
#        - candidates
#        - temp
#      sdkman_offline_mode: false
#      sdkman_update_alternatives:
#        - candidate: java
#          name: java
#          link: /usr/bin/java
#        - candidate: java
#          name: javac
#          link: /usr/bin/javac

#  tasks:
#  - name: Updating Homebrew and upgrading all packages
#    homebrew:
#      update_homebrew: yes
#      upgrade_all: yes
#
#  - name: Upgrading all casks
#    homebrew_cask:
#      upgrade_all: true

#  - name: Tapping homebrew/cask-fonts
#    homebrew_tap:
#      name: homebrew/cask-fonts
#
#  - name: Installing Nerd Font
#    homebrew_cask:
#      name: font-hack-nerd-font

#  - name: Installing Rectangle
#    homebrew_cask:
#      name: rectangle
#
#  - name: Installing essential packages with Homebrew
#    homebrew:
#      name: ['jq', 'python', 'wget', 'yarn', 'tree', 'composer', 'imagemagick', 'maven']