---
homebrew_common_taps:
  - oven-sh/bun
  - redis-stack/redis-stack
  - terraform-linters/tap

homebrew_common_packages_present:
  - antigravity-cli
  - azure-cli
  - bash
  - black
  - bun
  - copilot-cli
  - coreutils
  - curl
  - direnv
  - exiftool
  - ffmpeg
  - go
  - gpsbabel
  - graphviz
  - hf
  - htop
  - imagemagick
  - jq
  - kubectl
  - lazygit
  - maven
  - minikube
  - nvm
  - ollama
  - pipx
  - rsync
  - shellcheck
  - starship
  - tfenv
  - tflint
  - tree
  - uv
  - wget
  - yamllint
  - yarn
  - zed
  - zsh-autosuggestions
  - zsh-syntax-highlighting

homebrew_common_packages_absent:
  - allure
  - ansible-lint # remove first before removing ansible
  - ansible
  - checkov
  - composer
  - dialog
  - gemini-cli
  - gobject-introspection
  - nghttp2
  - tldr

homebrew_common_cask_packages_present:
  - 1password
  - alfred
  - brave-browser
  - calibrite-profiler
  - chatgpt
  - claude
  - claude-code
  - cyberduck
  - firefox
  - font-hack-nerd-font
  - font-meslo-lg-nerd-font
  - gcloud-cli
  - ghostty
  - google-chrome
  - google-drive
  - google-gemini
  - grandperspective
  - iTerm2
  - intellij-idea
  - logi-options-plus
  - postman
  - rancher
  - readdle-spark
  - rectangle
  - spotify
  - sublime-text
  - visual-studio-code

homebrew_common_cask_packages_absent:
  - anaconda
  - chronosync
  - cleanmymac
  - docker
  - google-backup-and-sync
  - i1profiler
  - mamp
  - nomachine
  - raindropio
  - scroll-reverser
  - skitch
  - textmate
