---
- name: Free up space by removing old packages installed by Homebrew
  ansible.builtin.command: brew cleanup
  changed_when: false

- name: Free up space by removing unused homebrew dependencies
  ansible.builtin.command: brew autoremove
  changed_when: false

- name: Perform Homebrew health check
  ansible.builtin.command: brew doctor
  register: cleanup_brew_doctor_output
  changed_when:
    - not 'Your system is ready to brew' in cleanup_brew_doctor_output.stdout
    - not 'A newer Command Line Tools release is available.' in cleanup_brew_doctor_output.stderr
  failed_when:
    - cleanup_brew_doctor_output.rc != 0
    # Homebrew may display this message on older macOS, ignore it
    - not 'A newer Command Line Tools release is available.' in cleanup_brew_doctor_output.stderr

- name: Display Homebrew health check recommendations
  ansible.builtin.debug:
    var: cleanup_brew_doctor_output
  when:
    - not 'Your system is ready to brew' in cleanup_brew_doctor_output.stdout
    - not 'A newer Command Line Tools release is available.' in cleanup_brew_doctor_output.stderr
