---
- name: Download/Update themes and plugins
  git:
    repo: '{{ item.base_url }}/{{ item.name }}.git'
    dest: '{{ ohmyzsh_custom_dir }}/{{ item.type }}/{{ item.name }}'
  with_items:
    - base_url: https://github.com/romkatv
      name: powerlevel10k
      type: themes
    - base_url: https://github.com/denysdovhan
      name: spaceship-prompt
      type: themes
    - base_url: https://github.com/zsh-users
      name: zsh-syntax-highlighting
      type: plugins
    - base_url: https://github.com/zsh-users
      name: zsh-autosuggestions
      type: plugins

# See https://github.com/denysdovhan/spaceship-prompt#oh-my-zsh
- name: Create symbolic link for Spaceship Prompt
  file:
    src: '{{ ohmyzsh_custom_dir }}/themes/spaceship-prompt/spaceship.zsh-theme'
    dest: '{{ ohmyzsh_custom_dir }}/themes/spaceship.zsh-theme'
    state: link

- name: Copy PowerLevel10k config file
  copy:
    src: .p10k.zsh
    dest: '{{ ansible_user_dir }}/.p10k.zsh'

# TODO Backup and replace the entire ~/.zshrc file
- name: Insert/Update configuration block in ~/.zshrc
  blockinfile:
    path: '{{ ansible_user_dir }}/.zshrc'
    backup: yes
    marker: "# {mark} - MAC-DEV-BOOTSTRAP MANAGED BLOCK - DON'T EDIT THIS BLOCK!"
    block: |
      export PATH="/usr/local/sbin:$PATH"

      export MAC_DEV_BOOTSTRAP_HOME="{{ playbook_dir }}"
      export MAC_DEV_BOOTSTRAP_SCRIPT="${MAC_DEV_BOOTSTRAP_HOME}/mac-dev-bootstrap.sh"
      alias update="cd ${MAC_DEV_BOOTSTRAP_HOME} && git pull --ff-only && ${MAC_DEV_BOOTSTRAP_SCRIPT}"

      alias python="/usr/local/bin/python3"
      alias pip="/usr/local/bin/pip3"

      for conf_file in {{ ohmyzsh_conf_dir }}/*; do
      	echo "Sourcing ${conf_file} ..."
      	source "${conf_file}"
      done

- name: Create shell conf dir if not exist
  file:
    path: '{{ ohmyzsh_conf_dir }}'
    state: directory
    mode: 0755

- name: Add to shell config dir
  copy:
    src: ohmyzsh.sh
    dest: '{{ ohmyzsh_conf_dir }}/ohmyzsh.sh'
