---
ai_instructions_targets:
  - dir: '{{ ansible_facts["user_dir"] }}/.gemini'
    filename: GEMINI.md
  - dir: '{{ ansible_facts["user_dir"] }}/.claude'
    filename: CLAUDE.md
  - dir: '{{ ansible_facts["user_dir"] }}/.copilot'
    filename: copilot-instructions.md
