---
- name: Install latest pip
  ansible.builtin.command: python3 -m ensurepip --upgrade  # noqa no-changed-when

- name: Install packages using PIP
  ansible.builtin.pip:
    name: '{{ item }}'
    state: present
  loop: '{{ python_packages }}'
