---
- name: Install iTerm2
  homebrew_cask:
    name: iTerm2
    state: present

- name: Copy Profiles.json to ~/Library/Application Support/iTerm2/DynamicProfiles
  copy:
    src: Profiles.json
    dest: '{{ ansible_user_dir }}/Library/Application Support/iTerm2/DynamicProfiles'
    mode: 0644

# TODO use plutil -convert??
- name: Copy com.googlecode.iterm2.plist to ~/Library/Preferences
  copy:
    src: com.googlecode.iterm2.plist
    dest: '{{ ansible_user_dir }}/Library/Preferences'
    mode: 0644
