---
- name: Configure iTerm2 profile
  ansible.builtin.template:
    src: Profiles.json.j2
    dest: '{{ ansible_user_dir }}/Library/Application Support/iTerm2/DynamicProfiles/Profiles.json'
    mode: '0644'

- name: Configure iTerm2 settings
  ansible.builtin.template:
    src: com.googlecode.iterm2.plist.j2
    dest: '{{ ansible_user_dir }}/Library/Preferences/com.googlecode.iterm2.plist'
    mode: '0644'

# In case there's a need to inspect the current plist (to see if something got changed):-
# cp ~/Library/Preferences/com.googlecode.iterm2.plist temp.plist
# plutil -convert xml1 temp.plist
- name: Convert plist file to binary
  ansible.builtin.command: plutil -convert binary1 {{ ansible_user_dir }}/Library/Preferences/com.googlecode.iterm2.plist
  changed_when: false
